[project]
name = "FraudScoringAgent"
version = "0.0.1"
description = "FraudScoringAgent"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]
dependencies = [
    "uipath-llamaindex>=0.0.27",
    "llama-index-llms-openai>=0.2.2"
]
requires-python = ">=3.10"
